### ISSUE TITLE
Need info of mapping document title with document index  

### ISSUE THREAD

**Issue by joey-yoonsung** [KerbEOS/eosio-doc#18]
Hi. I'm yoonsung.lee. I know this project from facebook group 'KerbEOS'.

I tried to translate document yesterday. But I confused capturing existing documents because document there is only document title and I cannot easily mapping with index on official website.

So, I suggest to create new document which is include information of mapping document index with document title.

We expect this document to help capture the progress of our project. It will help to reserve new document for newbie, like me. I will also help figure out this project for existing members. Honestly, we don't know which documents are done after see existing issues. 

Below content is just example. If you guys permit this documentation job to me, I will contrive better readability document for our project.

# Indexs

### 1.1 Introduction
| Category      | Content         |
|-------------|------------------|
| status      | resolved         |
| document    | [introduction.rst](https://github.com/KerbEOS/eosio-doc/blob/master/docs/eosio-home/introduction.rst) |
| contributor | [conr2d](https://github.com/KerbEOS/eosio-doc/commits?author=conr2d)           |

### 1.2 Before you begin
| Category      | Content         |
|-------------|------------------|
| status      | reserved         |
| contributor | yoonsung.lee           |

**Comment by conr2d** [comment]
Thank you for your suggestion.
It seems that the official website shows documents from two different repos, `eosio-home` and `eosio-nodeos`. (You can find them via the url of each page) However, our docs are generated from one repository and using readthedocs infra, `eosio-doc` repo contains resources from both of them.
I agree with you about creating the page for indices is useful, but not sure about showing contributor for each page. Even after initial version of translation is submitted, anyone can improve translation or update its contents responding to upstream document update.

**Comment by conr2d** [comment]
I found that official website has more repos than two, including `eosio-cleos`, `keosd` and `eosio-cpp`. I'll write the page covering the hierarchy of all pages soon.
