### ISSUE TITLE
eosio-home/docs/setting-up-your-environment | getting-the-software

### ISSUE THREAD

**Issue by jhyoon01** [KerbEOS/eosio-doc#2]
1-2 Before You Begin, 1-3 Start Your Nodes & Setup에 대해 번역 작업 중입니다.

**Comment by conr2d** [comment]
* 1-2 : https://developers.eos.io/eosio-home/docs/setting-up-your-environment
* 1-3 : https://developers.eos.io/eosio-home/docs/getting-the-software

**Comment by conr2d** [comment]
저도 확인하지 않고 작업했었는데 URL 보니 문서별로 파일명이 있네요. 맞춰서 작업하면 좋을 것 같습니다.
```
1-2, setting-up-your-environment.rst
1-3, getting-the-software.rst
```

**Comment by conr2d** [comment]
All related PR are merged.
